### ISSUE TITLE
[【tutorial】 How to start configservice , adminservice , portal  with apollo-all-in-one.jar 

### ISSUE THREAD

**Issue by PromiseChan** [apolloconfig/apollo-quick-start#101]
STEP 1.  find the following command in demo.sh
`$SERVICE_JAR start  --configservice --adminservice `

STEP 2 . add "  --portal " to the end
`  $SERVICE_JAR start --configservice --adminservice --portal  `

STEP3. check JVM options
in  ` export JAVA_OPTS="$PORTAL_JAVA_OPTS  ...`

add the  following JVM Options 

`-Ddev_meta=$config_server_url -Dfat.meta=$config_server_url -Duat.meta=$config_server_url -Dlpt.meta=$config_server_url -Dpro.meta=$config_server_url`

STEP3. copy jar to portal directory
`cp apollo-all-in-one.jar portal/`

**Comment by nobodyiam** [comment]
Normally, users don't need the manual step, is there a special consideration to run all of them in one process?
