### ISSUE TITLE
如何解决k8s内部部署，k8s外无法通过服务发现获取配置的问题？

### ISSUE THREAD

**Issue by sakufo** [apolloconfig/apollo-quick-start#104]
如题，在K8S部署后应用启动后拿到mete server地址是k8s的svc地址，但外部服务是无法直接访问svc地址的。
请问如何解决？

**Comment by nobodyiam** [comment]
可以用 [load balancer/ingress](https://www.apolloconfig.com/#/zh/deployment/distributed-deployment-guide?id=_241445-%e4%bb%a5load-balancer%e5%bd%a2%e5%bc%8f%e6%9a%b4%e9%9c%b2%e6%9c%8d%e5%8a%a1) 对外暴露服务，然后配置[meta server 域名](https://www.apolloconfig.com/#/zh/deployment/distributed-deployment-guide?id=_241444-%e9%85%8d%e7%bd%ae%e7%8e%af%e5%a2%83%e4%bf%a1%e6%81%af)
