### ISSUE TITLE
本地执行 ./demo client的问题

### ISSUE THREAD

**Issue by smartlee** [apolloconfig/apollo-quick-start#105]
本地执行找不到metaserver, 看上去找不到meta server, 172.18.0.3是获取本地的ip地址，这个需要在哪个配置文件中配置下本地的地址？
`[apollo-demo][main]2023-05-25 10:56:10,340 INFO  [com.ctrip.framework.foundation.internals.provider.DefaultApplicationProvider] App ID is set to SampleApp by app.id property from /META-INF/app.properties
[apollo-demo][main]2023-05-25 10:56:10,341 WARN  [com.ctrip.framework.foundation.internals.provider.DefaultApplicationProvider] app.label is not available from System Property and /META-INF/app.properties. It is set to null
[apollo-demo][main]2023-05-25 10:56:10,342 INFO  [com.ctrip.framework.foundation.internals.provider.DefaultServerProvider] Environment is set to [dev] by JVM system property 'env'.
[apollo-demo][main]2023-05-25 10:56:10,355 INFO  [com.ctrip.framework.apollo.internals.DefaultMetaServerProvider] Located meta services from apollo.meta configuration: http://localhost:8080!
[apollo-demo][main]2023-05-25 10:56:10,355 INFO  [com.ctrip.framework.apollo.core.MetaDomainConsts] Located meta server address http://localhost:8080 for env DEV from com.ctrip.framework.apollo.internals.DefaultMetaServerProvider
[apollo-demo][main]2023-05-25 10:56:10,384 DEBUG [com.ctrip.framework.apollo.internals.RemoteConfigRepository] Loading config from http://172.18.0.3:8080/configs/SampleApp/default/application?ip=192.168.3.162
[apollo-demo][main]2023-05-25 10:56:15,398 WARN  [com.ctrip.framework.apollo.internals.RemoteConfigRepository] Load config failed, will retry in 1 SECONDS. appId: SampleApp, cluster: default, namespaces: appli`

**Comment by nobodyiam** [comment]
1.  可以看下管理员工具 - 系统信息
![image](https://github.com/apolloconfig/apollo-quick-start/assets/837658/fc2fd30e-1ec6-4c41-9de9-37b4823741d8)

2. 可以参考[1.4 网络策略](https://www.apolloconfig.com/#/zh/deployment/distributed-deployment-guide?id=_14-%e7%bd%91%e7%bb%9c%e7%ad%96%e7%95%a5)
