### ISSUE TITLE
mysql5.7.42 执行sql示例有误

### ISSUE THREAD

**Issue by R1ghtHereWaiting** [apolloconfig/apollo-quick-start#107]
https://github.com/apolloconfig/apollo-quick-start/blob/master/sql/apolloconfigdb.sql

ServiceRegistry的建表语句有误
`DataChange_CreatedTime` `DataChange_LastTime`需要给默认值

**Comment by nobodyiam** [comment]
Would you please post the actual error messages?

**Comment by R1ghtHereWaiting** [comment]
<img width="927" alt="image" src="https://github.com/apolloconfig/apollo-quick-start/assets/83198160/0dd54fb8-1edb-4aba-824d-cf5eb251169b">

**Comment by R1ghtHereWaiting** [comment]
个人习惯一个sql一个sql跑，整个初始化sql一起执行不会有这个问题

**Comment by nobodyiam** [comment]
It was fixed by https://github.com/apolloconfig/apollo/pull/4792, and I submitted #108 to merge this fix.

**Comment by R1ghtHereWaiting** [comment]
Got it, thx
