### ISSUE TITLE
使用./demo.sh start 执行，只有admin server在8090端口起来了，其他的两个都没起来，输出日志提示查看./service、apollo-service.log,但是一直在报错，报错如下

### ISSUE THREAD

**Issue by SherryLinqy** [apolloconfig/apollo-quick-start#109]
c.n.d.s.t.d.RedirectingEurekaHttpClient  : Request execution error

com.sun.jersey.api.client.ClientHandlerException: java.net.ConnectException: Connection refused (Connection refused)

**Comment by nobodyiam** [comment]
看日志中最前面的报错信息
