### ISSUE TITLE
./demo.sh start 启动只显示8070启动成功

### ISSUE THREAD

**Issue by wwhwwxlz** [apolloconfig/apollo-quick-start#113]
@
![Uploading 2.PNG…]()

apollo-service.log文件
![Uploading 3.PNG…]()

**Comment by wwhwwxlz** [comment]
<img width="247" alt="4" src="https://github.com/apolloconfig/apollo-quick-start/assets/163984673/157d64df-9e12-4f19-8d24-58239d69dbe7">

**Comment by wwhwwxlz** [comment]
<img width="524" alt="2" src="https://github.com/apolloconfig/apollo-quick-start/assets/163984673/f95b606d-c960-433a-b5ae-6f813af6f07a">
apollo-service.log
<img width="633" alt="3" src="https://github.com/apolloconfig/apollo-quick-start/assets/163984673/947af9d1-8421-4aa8-95bb-e8ea08cc01d1">

**Comment by wwhwwxlz** [comment]
<img width="627" alt="5" src="https://github.com/apolloconfig/apollo-quick-start/assets/163984673/16f767fe-580e-40cc-985a-449a64845fcb">

**Comment by nobodyiam** [comment]
It's a bug introduced in the last commit and is fixed via https://github.com/apolloconfig/apollo-quick-start/commit/901b91ccac7e737b7aa78c01957e35d27af91bb9.
Please rebuild the database using the latest schema and try again.
